### ISSUE TITLE
Battery status messages saved up till bluetooth is enabled

### ISSUE THREAD

**Issue by datacute** [sharandac/My-TTGO-Watch#166]
I connected using WConfigurator watch.anakod.ru
The console log shows a huge number of battery status messages, starting (JSInterop.js actually belongs on the end of the line before, not the start of each line - I don't know how to get a nice copy of the console log):

```
JSInterop.js:6 {"filters":[{"services":["6e400001-b5a3-f393-e0a9-e50e24dcca9e"]}]}
JSInterop.js:9 BluetoothDevicegatt: BluetoothRemoteGATTServer {device: BluetoothDevice, connected: true}id: "d24NbMlbQWALgTpS0EIhQw=="name: "Espruino (T-Watch2020)"ongattserverdisconnected: null__proto__: BluetoothDevice
JSInterop.js:96 Characteristics listening
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,56]
JSInterop.js:106 [57,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,56]
JSInterop.js:106 [55,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,56]
JSInterop.js:106 [57,125,13,10]
```
... many lines later:
```
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,53]
JSInterop.js:106 [125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,53]
JSInterop.js:106 [125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,49]
JSInterop.js:106 [51,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,49]
JSInterop.js:106 [53,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,51]
JSInterop.js:106 [48,125,13,10]
JSInterop.js:106 [3,123,34,97,112,112,34,58,34,105,114,34,44,34,114,34,58,34,108,105]
blazor.webassembly.js:1 Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 3, position 0.
blazor.webassembly.js:1    at Newtonsoft.Json.JsonTextReader.Read()
blazor.webassembly.js:1    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
blazor.webassembly.js:1    at Newtonsoft.Json.Linq.JObject.Parse(String json)
blazor.webassembly.js:1    at WConfigurator.Services.WatchService.Process(String msg)
blazor.webassembly.js:1 {t:"status", bat:89}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:87}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:89}
blazor.webassembly.js:1 
```
... many lines later:
```
blazor.webassembly.js:1 {t:"status", bat:5}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:5}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:13}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:15}
blazor.webassembly.js:1 
blazor.webassembly.js:1 {t:"status", bat:30}
JSInterop.js:106 [115,116,34,44,34,118,34,58,91,34,67,104,114,111,109,101,34,44,34,84]
JSInterop.js:106 [86,34,44,34,83,107,121,34,44,34,83,111,117,110,100,34,44,34,67,68]
JSInterop.js:106 [34,44,34,77,117,116,101,34,93,125,3]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,51]
JSInterop.js:106 [51,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,51]
JSInterop.js:106 [55,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,52]
JSInterop.js:106 [52,125,13,10]
JSInterop.js:106 [13,10,123,116,58,34,115,116,97,116,117,115,34,44,32,98,97,116,58,52]
JSInterop.js:106 [56,125,13,10]
```

When the first character 3 is received, that is when WConfigurator output all the status json messages.
When the second character 3 was received, the display showed the setup of my buttons.

I started looking at code to figure out why this is...

The blectl_send_msg method call from pmu.cpp calls msg_chain_add_msg which records the `{t:"status", bat:89}` message to send, adding it to a growing chain of unsent messages.
The blectl_loop method doesn't then send any messages, as BLECTL_CONNECT is not set.

Should the blectl_send_msg of `{t:"status", bat:89}` only be called if BLECTL_CONNECT is set?

**Comment by sharandac** [comment]
yes, you are right. blectl_send_msg should only send the message when BLECTL_CONNECT is set to avoid creating an unnecessarily large message chain. like this

```
    if ( blectl_get_event( BLECTL_CONNECT ) ) {
        blectl_msg_chain = msg_chain_add_msg( blectl_msg_chain, msg );
    }
    else {
        log_e("msg can't send while bluetooth is not connected");
    }
```

Another idea that just occurred to me is that it would also be better to delete the msg chain completely after a connection is lost or established.
